# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-25 22:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_nl', models.CharField(max_length=100, verbose_name='Name')),
                ('name_en', models.CharField(blank=True, max_length=100, verbose_name='Name (en)')),
                ('slug_nl', models.SlugField(editable=False, max_length=100)),
                ('slug_en', models.SlugField(editable=False, max_length=100)),
                ('content_nl', models.TextField(verbose_name='Content')),
                ('content_en', models.TextField(blank=True, verbose_name='Content (en)')),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Page',
                'ordering': ['name_nl'],
                'verbose_name_plural': 'Pages',
            },
        ),
    ]
