# Generated by Django 3.2.17 on 2023-09-21 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='educational',
            field=models.BooleanField(default=False, verbose_name='Educational page?'),
        ),
    ]
