# Generated by Django 2.2.25 on 2022-05-02 18:54

from django.db import migrations, models
import django.db.models.deletion


def move_owner_old_to_owner(apps, schema_editor):
    Photographer = apps.get_model('members', 'Photographer')
    Attachment = apps.get_model('files', 'Attachment')

    offset = 0
    limit = 1000

    while True:
        attachments = Attachment.objects.all()[offset:offset+limit]
        for attachment in attachments:
            if attachment.owner_old is not None:
                attachment.owner = Photographer.objects.get_or_create(person=attachment.owner_old)[0]
                attachment.save()
        if len(attachments) < limit:
            break
        else:
            offset += limit


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_photographer'),
        ('files', '0002_auto_20201103_2220'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attachment',
            old_name='owner',
            new_name='owner_old'
        ),
        migrations.AddField(
            model_name='attachment',
            name='owner',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='members.Photographer')
        ),
        migrations.RunPython(
            # Copy to old owner attribute back to the owner, but as a photographer
            move_owner_old_to_owner
        ),
        migrations.RemoveField(
            model_name='attachment',
            name='owner_old'
        )
    ]
