# Generated by Django 2.2.25 on 2022-09-05 19:37

import amelie.files.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_auto_20220502_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(upload_to=amelie.files.models.get_upload_filename),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='thumb_large',
            field=models.ImageField(blank=True, editable=False, height_field='thumb_large_height', null=True, upload_to=amelie.files.models.get_upload_filename, width_field='thumb_large_width'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='thumb_medium',
            field=models.ImageField(blank=True, editable=False, height_field='thumb_medium_height', null=True, upload_to=amelie.files.models.get_upload_filename, width_field='thumb_medium_width'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='thumb_small',
            field=models.ImageField(blank=True, editable=False, height_field='thumb_small_height', null=True, upload_to=amelie.files.models.get_upload_filename, width_field='thumb_small_width'),
        ),
    ]
