# Generated by Django 3.2.25 on 2024-04-14 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0005_auto_20221028_1502'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attachment',
            options={'ordering': ['created', 'file'], 'verbose_name': 'Appendix', 'verbose_name_plural': 'Attachments'},
        ),
    ]
