# Generated by Django 3.2.21 on 2024-06-20 15:20

import amelie.files.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gmm', '0002_alter_gmm_agenda'),
        ('members', '0014_auto_20230918_2241'),
        ('files', '0006_alter_attachment_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='GMMDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=150, upload_to=amelie.files.models.get_gmm_upload_filename)),
                ('caption', models.CharField(blank=True, max_length=150, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('gmm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='gmm.gmm')),
                ('uploader', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.person')),
            ],
            options={
                'verbose_name': 'GMM Document',
                'verbose_name_plural': 'GMM Documents',
                'ordering': ['gmm', 'caption', 'created', 'file'],
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=150, upload_to=amelie.files.models.get_file_upload_filename)),
                ('caption', models.CharField(max_length=150)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('uploader', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.person')),
            ],
            options={
                'verbose_name': 'File',
                'verbose_name_plural': 'Files',
                'ordering': ['created', 'caption', 'file'],
            },
        ),
    ]
