# Generated by Django 4.2.25 on 2025-10-14 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0015_alter_function_options'),
        ('files', '0007_gmmdocument_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.photographer'),
        ),
    ]
