# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-25 22:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('oauth2_provider', '0001_initial'),
        ('calendar', '0001_initial'),
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='calendar.Event')),
                ('enrollment', models.BooleanField(default=False, verbose_name='enrollment')),
                ('enrollment_begin', models.DateTimeField(blank=True, help_text="If you want to add options, make sure your activity isn't open for enrollment right away", null=True, verbose_name='enrollment start')),
                ('enrollment_end', models.DateTimeField(blank=True, null=True, verbose_name='enrollment end')),
                ('maximum', models.PositiveIntegerField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, default='0.00', max_digits=8, verbose_name='price')),
                ('can_unenroll', models.BooleanField(default=True, verbose_name='can unenroll')),
                ('image_icon', models.ImageField(blank=True, help_text='Image of 175 by 275 pixels.', max_length=255, null=True, upload_to='activities/icon/', verbose_name='icon')),
                ('facebook_event_id', models.CharField(blank=True, help_text='Facebook event id, numerical value in the facebook event url.', max_length=150)),
                ('components', models.ManyToManyField(blank=True, related_name='_activity_components_+', to='activities.Activity')),
                ('oauth_application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='oauth2_provider.Application')),
                ('photos', models.ManyToManyField(blank=True, related_name='foto_set', to='files.Attachment')),
            ],
            options={
                'verbose_name': 'Activities',
                'ordering': ['begin'],
                'verbose_name_plural': 'Activities',
            },
            bases=('calendar.event',),
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Name')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Price')),
                ('available', models.BooleanField(default=True, verbose_name='Available')),
            ],
        ),
        migrations.CreateModel(
            name='DishPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='activities.Dish')),
            ],
        ),
        migrations.CreateModel(
            name='Enrollmentoption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Title')),
            ],
            options={
                'verbose_name': 'Enrollment option',
                'verbose_name_plural': 'Enrollment options',
            },
        ),
        migrations.CreateModel(
            name='EnrollmentoptionAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Answer to enrollment option',
                'verbose_name_plural': 'Anwers to enrollment option',
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SelectboxOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=250)),
                ('price_extra', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Price extra')),
            ],
        ),
        migrations.CreateModel(
            name='EnrollmentoptionCheckbox',
            fields=[
                ('enrollmentoption_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='activities.Enrollmentoption')),
                ('price_extra', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Price extra')),
            ],
            bases=('activities.enrollmentoption',),
        ),
        migrations.CreateModel(
            name='EnrollmentoptionCheckboxAnswer',
            fields=[
                ('enrollmentoptionanswer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='activities.EnrollmentoptionAnswer')),
                ('answer', models.BooleanField(default=False, verbose_name='Respons')),
            ],
            bases=('activities.enrollmentoptionanswer',),
        ),
        migrations.CreateModel(
            name='EnrollmentoptionFood',
            fields=[
                ('enrollmentoption_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='activities.Enrollmentoption')),
                ('required', models.BooleanField(default=True, verbose_name='Required')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='activities.Restaurant', verbose_name='Restaurant')),
            ],
            bases=('activities.enrollmentoption',),
        ),
        migrations.CreateModel(
            name='EnrollmentoptionFoodAnswer',
            fields=[
                ('enrollmentoptionanswer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='activities.EnrollmentoptionAnswer')),
                ('dishprice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='activities.DishPrice', verbose_name='Dish cost')),
            ],
            bases=('activities.enrollmentoptionanswer',),
        ),
        migrations.CreateModel(
            name='EnrollmentoptionQuestion',
            fields=[
                ('enrollmentoption_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='activities.Enrollmentoption')),
                ('required', models.BooleanField(default=True, verbose_name='Required')),
            ],
            bases=('activities.enrollmentoption',),
        ),
        migrations.CreateModel(
            name='EnrollmentoptionQuestionAnswer',
            fields=[
                ('enrollmentoptionanswer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='activities.EnrollmentoptionAnswer')),
                ('answer', models.CharField(blank=True, max_length=250, verbose_name='Respons')),
            ],
            bases=('activities.enrollmentoptionanswer',),
        ),
        migrations.CreateModel(
            name='EnrollmentoptionSelectbox',
            fields=[
                ('enrollmentoption_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='activities.Enrollmentoption')),
            ],
            bases=('activities.enrollmentoption',),
        ),
        migrations.CreateModel(
            name='EnrollmentoptionSelectboxAnswer',
            fields=[
                ('enrollmentoptionanswer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='activities.EnrollmentoptionAnswer')),
            ],
            bases=('activities.enrollmentoptionanswer',),
        ),
        migrations.AddField(
            model_name='enrollmentoptionanswer',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='enrollmentoptionanswer',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calendar.Participation'),
        ),
        migrations.AddField(
            model_name='enrollmentoptionanswer',
            name='enrollmentoption',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.Enrollmentoption'),
        ),
        migrations.AddField(
            model_name='enrollmentoption',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.Activity'),
        ),
        migrations.AddField(
            model_name='enrollmentoption',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='dish',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='activities.Restaurant', verbose_name='Restaurant'),
        ),
        migrations.AddField(
            model_name='selectboxoption',
            name='selection_option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.EnrollmentoptionSelectbox'),
        ),
        migrations.AddField(
            model_name='enrollmentoptionselectboxanswer',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.SelectboxOption', verbose_name='Respons'),
        ),
        migrations.AddField(
            model_name='dishprice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.EnrollmentoptionFood', verbose_name='Enrollment optionquestion'),
        ),
    ]
