# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-05-28 12:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventDeskRegistrationMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=191, unique=True, verbose_name='E-mail message ID')),
                ('message_date', models.DateTimeField(verbose_name='E-mail message timestamp')),
                ('state', models.CharField(choices=[('NEW', 'Registered'), ('ACCEPTED', 'Accepted'), ('UNKNOWN', 'Unknown')], max_length=191, verbose_name='New state of the event registration')),
                ('requester', models.CharField(max_length=191, verbose_name='Person that requested the registration as stated in the e-mail')),
                ('event_name', models.CharField(max_length=191, verbose_name='Name of the event as stated in the e-mail')),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='activities.Activity')),
                ('match_ratio', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='Percentage certainty of match with activity.')),
                ('event_start', models.CharField(max_length=191, verbose_name='Start date/time of the event as stated in the e-mail')),
                ('event_end', models.CharField(max_length=191, verbose_name='End date/time of the event as stated in the e-mail')),
                ('event_location', models.CharField(max_length=191, verbose_name='Location of the event as stated in the e-mail')),
            ],
        ),
    ]
