# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-06-13 16:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_eventdeskregistrationmessage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventdeskregistrationmessage',
            options={'ordering': ['-message_date']},
        ),
    ]
