# Generated by Django 2.2.25 on 2022-01-24 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_auto_20201103_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='allergens',
            field=models.TextField(blank=True, default='No information available', verbose_name='Allergens'),
        ),
    ]
