# Generated by Django 2.2.25 on 2022-04-19 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0005_dish_allergens'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollmentoptioncheckbox',
            name='maximum',
            field=models.IntegerField(default=0, help_text='Set as 0 for unlimited', verbose_name='Maximum limit of selections'),
        ),
    ]
