# Generated by Django 2.2.25 on 2022-06-04 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0006_enrollmentoptioncheckbox_maximum'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='waiting_list_locked',
            field=models.BooleanField(default=False, verbose_name='Lock waiting list'),
        ),
    ]
