# Generated by Django 2.2.25 on 2022-06-04 23:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0007_activity_waiting_list_locked'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrollmentoptionNumeric',
            fields=[
                ('enrollmentoption_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='activities.Enrollmentoption')),
                ('price_extra', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Price extra')),
                ('maximum', models.IntegerField(default=0, help_text='Set as 0 for unlimited', verbose_name='Maximum limit of selections')),
                ('maximum_per_person', models.IntegerField(default=0, help_text='Set as 0 for unlimited', verbose_name='Maximum per person')),
            ],
            bases=('activities.enrollmentoption',),
        ),
        migrations.CreateModel(
            name='EnrollmentoptionNumericAnswer',
            fields=[
                ('enrollmentoptionanswer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='activities.EnrollmentoptionAnswer')),
                ('answer', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Respons')),
            ],
            bases=('activities.enrollmentoptionanswer',),
        ),
    ]
