# Generated by Django 2.2.25 on 2022-10-03 16:15
# Edited by Bram for default label

from django.db import migrations, models
import django.db.models.deletion


def create_default_label(apps, schema_editor):
    ActivityLabel = apps.get_model('activities', 'ActivityLabel')
    Activity = apps.get_model('activities', 'Activity')
    label = ActivityLabel.objects.create(name="Unknown", color="808080", icon="tag_blue", explanation="No label given")
    for activity in Activity.objects.all():
        activity.activity_label = label
        activity.save()


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0008_enrollmentoptionnumeric_enrollmentoptionnumericanswer'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Name')),
                ('color', models.CharField(max_length=6, verbose_name='Hexcolor without #')),
                ('icon', models.CharField(max_length=32, verbose_name='Icon from known icons')),
                ('explanation', models.TextField(verbose_name='Explanation on icon')),
                ('active', models.BooleanField(verbose_name='Active?', default=True))
            ],
        ),
        migrations.AddField(
            model_name='activity',
            name='activity_label',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='activities.ActivityLabel', blank=True, null=True),
            preserve_default=False,
        ),
        migrations.RunPython(create_default_label),
        migrations.AlterField(
            model_name='activity',
            name='activity_label',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='activities.ActivityLabel')
        ),
    ]
