# Generated by Django 3.2.16 on 2022-10-31 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0009_auto_20221003_1815'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activitylabel',
            old_name='explanation',
            new_name='explanation_nl',
        ),
        migrations.RenameField(
            model_name='activitylabel',
            old_name='name',
            new_name='name_nl',
        ),
        migrations.AddField(
            model_name='activitylabel',
            name='explanation_en',
            field=models.TextField(default='Unknown', verbose_name='Explanation on icon (en)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activitylabel',
            name='name_en',
            field=models.CharField(default='Unknown', max_length=32, verbose_name='Name (en)'),
            preserve_default=False,
        ),
    ]
