# Generated by Django 5.2.14 on 2026-05-08 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0011_alter_activity_components'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='price',
            field=models.DecimalField(decimal_places=2, default='0.00', help_text='Enrolled participants will be emailed when you change the price.', max_digits=8, verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='enrollmentoptioncheckbox',
            name='price_extra',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Enrolled participants will be emailed when you change the price.', max_digits=8, verbose_name='Price extra'),
        ),
        migrations.AlterField(
            model_name='enrollmentoptionnumeric',
            name='price_extra',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Enrolled participants will be emailed when you change the price.', max_digits=8, verbose_name='Price extra'),
        ),
    ]
