# Generated by Django 5.2.15 on 2026-07-04 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0012_alter_activity_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='enrollment_private',
            field=models.BooleanField(default=True, verbose_name='Hide participants'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='enrollment_private',
            field=models.BooleanField(default=False, verbose_name='Hide participants'),
        ),
    ]
