# Generated by Django 5.2.12 on 2026-08-12 13:36

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0013_activity_enrollment_private'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='price',
            field=models.DecimalField(decimal_places=2, default='0.00', help_text='Enrolled participants will be emailed when you change the price.', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='price'),
        ),
    ]
