# Generated by Django 3.2.18 on 2023-05-01 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0002_auto_20201103_2220'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoginToken',
        ),
    ]
