# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-25 22:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='YouTubeVideo',
            fields=[
                ('video_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('date_published', models.DateTimeField()),
                ('thumbnail_url', models.CharField(max_length=100)),
                ('is_featured', models.BooleanField(default=False, verbose_name='Featured')),
                ('public', models.BooleanField(default=True, verbose_name='Public')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.Committee')),
            ],
            options={
                'verbose_name': 'YouTube video',
                'ordering': ['-date_published'],
                'verbose_name_plural': 'YouTube videos',
            },
        ),
    ]
