# Generated by Django 2.2.24 on 2021-12-10 21:43

from django.db import migrations, models
import django.db.models.deletion


def migrate_youtube_videos(apps, schema_editor):
    # Move old youtube video data to the new inheritance model
    OldYoutubeVideo = apps.get_model('videos', 'OldYoutubeVideo')
    NewYoutubeVideo = apps.get_model('videos', 'NewYoutubeVideo')
    for old_video in OldYoutubeVideo.objects.all():
        new_video = NewYoutubeVideo()
        new_video.video_id = old_video.video_id
        new_video.title = old_video.title
        new_video.description = old_video.description
        new_video.date_published = old_video.date_published
        new_video.thumbnail_url = old_video.thumbnail_url
        new_video.publisher = old_video.publisher
        new_video.is_featured = old_video.is_featured
        new_video.public = old_video.public
        new_video.save()
        old_video.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_auto_20201103_2220'),
        ('videos', '0002_auto_20201103_2220'),
    ]

    operations = [
        migrations.RenameModel('YoutubeVideo', 'OldYoutubeVideo'),
        migrations.CreateModel(
            name='BaseVideo',
            fields=[
                ('video_id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=191)),
                ('description', models.TextField()),
                ('date_published', models.DateTimeField()),
                ('thumbnail_url', models.CharField(max_length=191)),
                ('is_featured', models.BooleanField(default=False, verbose_name='Featured')),
                ('public', models.BooleanField(default=True, verbose_name='Public')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='members.Committee')),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videos',
                'ordering': ['-date_published'],
            },
        ),
        migrations.CreateModel(
            name='NewYoutubeVideo',
            fields=[
                ('basevideo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='videos.BaseVideo')),
            ],
            options={
                'verbose_name': 'YouTube video',
                'verbose_name_plural': 'YouTube videos',
                'ordering': ['-date_published'],
            },
            bases=('videos.basevideo',),
        ),
        migrations.CreateModel(
            name='StreamingIAVideo',
            fields=[
                ('basevideo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='videos.BaseVideo')),
            ],
            options={
                'verbose_name': 'Streaming.IA video',
                'verbose_name_plural': 'Streaming.IA videos',
                'ordering': ['-date_published'],
            },
            bases=('videos.basevideo',),
        ),
        migrations.RunPython(migrate_youtube_videos),
        migrations.DeleteModel('OldYoutubeVideo'),
        migrations.RenameModel('NewYoutubeVideo', 'YoutubeVideo')
    ]
