# Generated by Django 4.2.26 on 2025-12-01 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_streamingia_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeertubeIAVideo',
            fields=[
                ('basevideo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='videos.basevideo')),
            ],
            options={
                'verbose_name': 'Video.IA video',
                'verbose_name_plural': 'Video.IA videos',
                'ordering': ['-date_published'],
            },
            bases=('videos.basevideo',),
        ),
    ]
