# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-25 22:00
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_published', models.DateTimeField()),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='data/uploads/%Y/%m/%d/')),
                ('file', models.FileField(upload_to='data/uploads/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('is_featured', models.BooleanField(default=False, verbose_name='featured')),
                ('public', models.BooleanField(default=True, verbose_name='public')),
            ],
            options={
                'verbose_name': 'publication',
                'ordering': ['-date_published'],
                'verbose_name_plural': 'publications',
            },
        ),
        migrations.CreateModel(
            name='PublicationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=150, unique=True, verbose_name='type name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('default_thumbnail', models.ImageField(help_text='This thumbnail is shown when a publication of this type is uploaded without thumbnail.', upload_to='data/uploads/%Y/%m/%d/', verbose_name='default thumbnail')),
            ],
            options={
                'verbose_name': 'publication type',
                'ordering': ['type_name'],
                'verbose_name_plural': 'publication types',
            },
        ),
        migrations.AddField(
            model_name='publication',
            name='publication_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publications.PublicationType'),
        ),
    ]
