# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-25 22:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application', models.CharField(choices=[('AmelieDataExporter', 'Data in the Inter-/Actief/ website and the members database.'), ('AmelieFileDataExporter', 'Files you have uploaded to the Inter-/Actief/ website (warning, may be very large).'), ('AlexiaDataExporter', 'Data from Alexia, the drink management system.'), ('GitLabDataExporter', 'Data in GitLab, the version control system.'), ('HomedirDataExporter', 'The home directory of your Inter-Actief active members account (warning, may be very large).')], help_text='The name of the application you want to export data from.', max_length=40, verbose_name='Application')),
                ('status', models.IntegerField(choices=[(0, 'Not yet started'), (1, 'Busy exporting data'), (2, 'Done exporting data'), (3, 'Error during exporting')], default=0, help_text='The status of the export from this application.', verbose_name='Export status')),
            ],
            options={
                'verbose_name': 'Application status',
                'verbose_name_plural': 'Application statuses',
            },
        ),
        migrations.CreateModel(
            name='DataExport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('download_code', models.CharField(help_text='Code with which you can download this export.', max_length=50, unique=True, verbose_name='Download code')),
                ('filename', models.FilePathField(blank=True, help_text='The file name of the exported data.', null=True, path='/data/application_data/amelie/data_exports', verbose_name='Filename')),
                ('request_timestamp', models.DateTimeField(auto_now_add=True, help_text='The time that this data export was requested.', verbose_name='Timestamp of request')),
                ('complete_timestamp', models.DateTimeField(blank=True, help_text='The time that this data export was completed.', null=True, verbose_name='Timestamp of completion')),
                ('download_count', models.IntegerField(default=0, help_text='How many times this export has been downloaded.', verbose_name='Number of times downloaded')),
                ('is_ready', models.BooleanField(default=False, help_text='If this export is ready to be downloaded or not.', verbose_name='Export is complete')),
                ('person', models.OneToOneField(help_text='The person whose data export this is.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.Person', verbose_name='Person')),
            ],
            options={
                'verbose_name': 'Data export',
                'verbose_name_plural': 'Data exports',
            },
        ),
        migrations.AddField(
            model_name='applicationstatus',
            name='data_export',
            field=models.ForeignKey(help_text='Which data export this status belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='exported_applications', to='data_export.DataExport', verbose_name='Data export'),
        ),
    ]
