# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-25 22:00
from __future__ import unicode_literals

import amelie.claudia.mappable
import amelie.claudia.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AliasGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=False)),
                ('email', models.EmailField(blank=True, max_length=254, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-active', 'name'],
            },
            bases=(models.Model, amelie.claudia.mappable.Mappable),
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=False)),
                ('email', models.EmailField(blank=True, max_length=254, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
            bases=(models.Model, amelie.claudia.mappable.Mappable),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=25)),
                ('execute', models.DateTimeField()),
            ],
            options={
                'ordering': ['-execute'],
            },
        ),
        migrations.CreateModel(
            name='ExtraGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=False)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('adname', models.CharField(blank=True, max_length=50)),
                ('dogroup', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-active', 'name'],
            },
            bases=(models.Model, amelie.claudia.mappable.Mappable),
        ),
        migrations.CreateModel(
            name='ExtraPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=False)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('adname', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-active', 'name'],
            },
            bases=(models.Model, amelie.claudia.mappable.Mappable),
        ),
        migrations.CreateModel(
            name='ExtraPersonalAlias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, validators=[amelie.claudia.models.ExtraPersonalAliasEmailValidator()])),
            ],
        ),
        migrations.CreateModel(
            name='Mapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=25)),
                ('ident', models.IntegerField()),
                ('name', models.CharField(blank=True, max_length=100)),
                ('active', models.BooleanField(default=False)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('adname', models.CharField(blank=True, max_length=50)),
                ('guid', models.CharField(blank=True, max_length=24)),
                ('gsuite_id', models.CharField(blank=True, max_length=100, null=True)),
                ('gsuite_forwarding_enabled', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.BooleanField(default=False)),
                ('mail', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_members', to='claudia.Mapping')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_groupmemberships', to='claudia.Mapping')),
            ],
            options={
                'ordering': ['group', 'member'],
            },
        ),
        migrations.CreateModel(
            name='Timeline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('type', models.CharField(blank=True, max_length=25)),
                ('description', models.TextField()),
                ('mapping', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='claudia.Mapping')),
            ],
            options={
                'ordering': ['-datetime', '-id'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='mapping',
            unique_together=set([('type', 'ident')]),
        ),
        migrations.AddField(
            model_name='extrapersonalalias',
            name='mapping',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_personal_aliases', to='claudia.Mapping'),
        ),
        migrations.AddField(
            model_name='event',
            name='mapping',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='claudia.Mapping'),
        ),
        migrations.AlterUniqueTogether(
            name='membership',
            unique_together=set([('group', 'member')]),
        ),
    ]
