# Generated by Django 2.2.20 on 2021-05-17 21:19

import amelie.claudia.mappable
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('claudia', '0002_auto_20201103_2220'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedDrive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
            bases=(models.Model, amelie.claudia.mappable.Mappable),
        ),
        migrations.AddField(
            model_name='membership',
            name='shared_drive',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='DrivePermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_id', models.CharField(max_length=512)),
                ('drive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='claudia.SharedDrive')),
                ('mapping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='claudia.Mapping')),
            ],
            options={
                'ordering': ['drive', 'mapping'],
            },
        ),
    ]
