# Generated by Django 2.2.25 on 2022-08-21 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claudia', '0003_auto_20210517_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='aliasgroup',
            name='open_to_signup',
            field=models.BooleanField(default=False, help_text='Note: Description becomes public', verbose_name='Open to sign up for members'),
        ),
    ]
