# Generated by Django 3.2.21 on 2024-06-20 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claudia', '0004_aliasgroup_open_to_signup'),
    ]

    operations = [
        migrations.AddField(
            model_name='extragroup',
            name='gitlab',
            field=models.BooleanField(default=False, help_text='Members of this group get access to GitLab', verbose_name='Create GitLab group'),
        ),
    ]
