# Generated by Django 4.2.26 on 2025-12-19 13:34

import amelie.claudia.mappable
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claudia', '0005_extragroup_gitlab'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordVault',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('vaultwarden_uuid', models.CharField(max_length=40)),
            ],
            options={
                'ordering': ['name'],
            },
            bases=(models.Model, amelie.claudia.mappable.Mappable),
        ),
        migrations.AddField(
            model_name='membership',
            name='password_vault',
            field=models.BooleanField(default=False),
        ),
    ]
