# Generated by Django 4.2.26 on 2025-12-23 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claudia', '0005_extragroup_gitlab'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapping',
            name='kanidm_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mapping',
            name='name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
