# Generated by Django 5.2.9 on 2026-02-23 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claudia', '0006_mapping_kanidm_id_alter_mapping_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapping',
            name='matrix_space_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
