# Generated by Django 5.2.9 on 2026-02-23 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claudia', '0007_mapping_matrix_space_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='extragroup',
            name='matrix',
            field=models.BooleanField(default=False, help_text='Members of this group get a private Matrix space', verbose_name='Create Matrix space'),
        ),
    ]
