# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-25 22:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PushNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=50)),
                ('title_nl', models.CharField(max_length=50)),
                ('message_en', models.CharField(max_length=150)),
                ('message_nl', models.CharField(max_length=150)),
                ('json_data', models.TextField(null=True)),
                ('has_fallback_sms', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'PushNotification',
                'verbose_name_plural': 'PushNotifications',
            },
        ),
    ]
