# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-17 20:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pushnotification',
            name='recipients',
            field=models.ManyToManyField(blank=True, to='members.Person'),
        ),
    ]
