# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-01 18:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190617_2321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pushnotification',
            name='has_fallback_sms',
        ),
    ]
