# Generated by Django 3.2.3 on 2021-05-18 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190701_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pushnotification',
            name='json_data',
            field=models.JSONField(null=True),
        ),
    ]
