# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-25 22:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomDuty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin', models.DateTimeField(verbose_name='Starts')),
                ('end', models.DateTimeField(verbose_name='Ends')),
                ('update_count', models.PositiveIntegerField(default=0)),
                ('participant_set', models.ManyToManyField(blank=True, related_name='room_duties', to='members.Person', verbose_name='Boardmembers')),
            ],
            options={
                'verbose_name': 'Office duty',
                'ordering': ['begin', 'end'],
                'verbose_name_plural': 'Office duties',
            },
        ),
        migrations.CreateModel(
            name='RoomDutyAvailability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('availability', models.CharField(choices=[('D', 'Dibs!'), ('G', 'Yes please!'), ('O', 'Available'), ('#', 'Rather not'), ('X', 'No, sorry'), ('?', 'Not sure yet')], default='?', max_length=1)),
                ('hungover', models.BooleanField(default=False)),
                ('not_in_the_break', models.BooleanField(default=False)),
                ('comments', models.CharField(blank=True, max_length=250, verbose_name='Comments')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.Person')),
                ('room_duty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='room_duty.RoomDuty')),
            ],
            options={
                'verbose_name': 'Office duty availability',
                'verbose_name_plural': 'Office duty availabilities',
            },
        ),
        migrations.CreateModel(
            name='RoomDutyPool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Name')),
                ('unsorted_persons', models.ManyToManyField(related_name='room_duty_pools', to='members.Person')),
            ],
            options={
                'verbose_name': 'Office duty',
                'ordering': ['-name'],
                'verbose_name_plural': 'Office duty pools',
            },
        ),
        migrations.CreateModel(
            name='RoomDutyTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Title')),
                ('begin', models.DateTimeField(verbose_name='Starts')),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_duty_tables', to='room_duty.RoomDutyPool')),
            ],
            options={
                'verbose_name': 'Office duty schedule',
                'ordering': ['-begin'],
                'verbose_name_plural': 'Office duty schedules',
            },
        ),
        migrations.CreateModel(
            name='RoomDutyTableTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Title')),
            ],
            options={
                'verbose_name': 'Office duty schedule template',
                'ordering': ['title'],
                'verbose_name_plural': 'Office duty schedule templates',
            },
        ),
        migrations.CreateModel(
            name='RoomDutyTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin', models.DurationField(verbose_name='Starts')),
                ('end', models.DurationField(verbose_name='Ends')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_duties', to='room_duty.RoomDutyTableTemplate')),
            ],
            options={
                'verbose_name': 'Office duty template',
                'ordering': ['begin', 'end'],
                'verbose_name_plural': 'Office duty templates',
            },
        ),
        migrations.AddField(
            model_name='roomduty',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_duties', to='room_duty.RoomDutyTable'),
        ),
    ]
