# Generated by Django 2.2.17 on 2020-11-03 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('room_duty', '0003_auto_20190325_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomdutytable',
            name='balcony_duty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='room_duty.BalconyDutyAssociation'),
        ),
    ]
