# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-04-27 22:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='association',
            options={'ordering': ['name'], 'verbose_name': 'association', 'verbose_name_plural': 'associations'},
        ),
        migrations.AlterModelOptions(
            name='committee',
            options={'ordering': ['name'], 'verbose_name': 'committee', 'verbose_name_plural': 'committees'},
        ),
        migrations.AlterModelOptions(
            name='committeecategory',
            options={'ordering': ['name'], 'verbose_name': 'committee category', 'verbose_name_plural': 'committee categories'},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['name'], 'verbose_name': 'department', 'verbose_name_plural': 'departments'},
        ),
        migrations.AlterModelOptions(
            name='dogroup',
            options={'ordering': ['name'], 'verbose_name': 'do-group', 'verbose_name_plural': 'do-groups'},
        ),
        migrations.AlterModelOptions(
            name='dogroupgeneration',
            options={'ordering': ['generation', 'dogroup'], 'verbose_name': 'do-group generation', 'verbose_name_plural': 'do-group generations'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['number'], 'verbose_name': 'employee', 'verbose_name_plural': 'employees'},
        ),
        migrations.AlterModelOptions(
            name='faculty',
            options={'ordering': ['name'], 'verbose_name': 'faculty', 'verbose_name_plural': 'faculties'},
        ),
        migrations.AlterModelOptions(
            name='function',
            options={'ordering': ['end', '-begin', 'person'], 'verbose_name': 'position', 'verbose_name_plural': 'functions'},
        ),
        migrations.AlterModelOptions(
            name='membership',
            options={'ordering': ['member', 'year'], 'verbose_name': 'membership', 'verbose_name_plural': 'memberships'},
        ),
        migrations.AlterModelOptions(
            name='membershiptype',
            options={'ordering': ['description'], 'verbose_name': 'membership type', 'verbose_name_plural': 'membership types'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['date'], 'verbose_name': 'payment', 'verbose_name_plural': 'payments'},
        ),
        migrations.AlterModelOptions(
            name='paymenttype',
            options={'ordering': ['description'], 'verbose_name': 'way of payment', 'verbose_name_plural': 'ways of payment'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['last_name'], 'verbose_name': 'person', 'verbose_name_plural': 'people'},
        ),
        migrations.AlterModelOptions(
            name='preference',
            options={'ordering': ['name', 'preference_nl'], 'verbose_name': 'preference', 'verbose_name_plural': 'preference'},
        ),
        migrations.AlterModelOptions(
            name='preferencecategory',
            options={'verbose_name': 'category of preference', 'verbose_name_plural': 'categories of preference'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'student', 'verbose_name_plural': 'students'},
        ),
        migrations.AlterModelOptions(
            name='study',
            options={'ordering': ['abbreviation'], 'verbose_name': 'study', 'verbose_name_plural': 'studies'},
        ),
        migrations.AlterModelOptions(
            name='studyperiod',
            options={'verbose_name': 'study period', 'verbose_name_plural': 'study periods'},
        ),
    ]
