# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2020-01-06 18:58
from __future__ import unicode_literals
import os

from amelie.members.models import person_picture_upload_path

from django.db import migrations, models
from django.conf import settings

OLD_PATH = 'pasfoto/'
NEW_PATH = 'profile_picture/'

def rename_profile_pictures(apps, schema_editor):
    Person = apps.get_model('members', 'Person')
    persons = Person.objects.exclude(picture__isnull=True)
    for person in persons:
        old_path = person.picture.name
        if old_path.startswith(OLD_PATH):  # Skip weird paths
            person.picture.name = person_picture_upload_path(person, old_path[len(OLD_PATH):])
            try:
                os.rename(os.path.join(settings.MEDIA_ROOT, old_path),
                          os.path.join(settings.MEDIA_ROOT, person.picture.name))
            except FileNotFoundError:
                print("Trying to move {} to {} but file not found, are we running on beta?".format(
                      old_path, person.picture.name))
            person.save()


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_unverifiedenrollment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=person_picture_upload_path, verbose_name='Photo'),
        ),
        migrations.RunPython(rename_profile_pictures),
    ]
