# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-18 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_profilepicturefolder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dogroupgeneration',
            name='parents',
            field=models.ManyToManyField(blank=True, to='members.Person', verbose_name='Introduction parents'),
        ),
    ]
