# Generated by Django 2.2.17 on 2020-11-03 21:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_auto_20200818_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='committee',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.CommitteeCategory', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='department',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.Faculty', verbose_name='Faculty'),
        ),
        migrations.AlterField(
            model_name='dogroupgeneration',
            name='dogroup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='members.Dogroup', verbose_name='Dogroup'),
        ),
        migrations.AlterField(
            model_name='dogroupgeneration',
            name='study',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='members.Study', verbose_name='Course'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='members.Person', verbose_name='Member'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='members.MembershipType', verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='membership',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='members.Membership', verbose_name='Membership'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='members.PaymentType', verbose_name='Payment'),
        ),
        migrations.AlterField(
            model_name='person',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='preference',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='members.PreferenceCategory'),
        ),
        migrations.AlterField(
            model_name='studyperiod',
            name='dogroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.DogroupGeneration', verbose_name='Dogroup'),
        ),
        migrations.AlterField(
            model_name='studyperiod',
            name='study',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='members.Study', verbose_name='Course'),
        ),
        migrations.AlterField(
            model_name='unverifiedenrollment',
            name='dogroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.DogroupGeneration', verbose_name='Dogroup'),
        ),
        migrations.AlterField(
            model_name='unverifiedenrollment',
            name='membership_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='members.MembershipType', verbose_name='Chosen membership type'),
        ),
    ]
