# Generated by Django 2.2.25 on 2022-01-10 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_auto_20201103_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='nda',
            field=models.BooleanField(default=False, verbose_name='Has signed NDA'),
        ),
    ]
