# Generated by Django 3.2.3 on 2021-06-19 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_photographer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='type',
            field=models.CharField(choices=[('BSc', 'Bachelor of Science'), ('MSc', 'Master of Science'), ('Ir', 'Engineer')], max_length=3, verbose_name='Type'),
        ),
    ]
