# Generated by Django 3.2.17 on 2023-04-07 11:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0011_alter_person_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='ut_external_username',
            field=models.CharField(blank=True, max_length=8, null=True, validators=[django.core.validators.RegexValidator('^x[0-9]{7}$', 'You can only enter ^x[0-9]{7}$.', 'Invalid account name')], verbose_name='UT external account name'),
        ),
    ]
