# Generated by Django 4.2.16 on 2025-04-21 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0014_auto_20230918_2241'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='function',
            options={'ordering': [models.OrderBy(models.F('end'), descending=True, nulls_first=True), '-begin', 'person'], 'verbose_name': 'position', 'verbose_name_plural': 'functions'},
        ),
    ]
