# Generated by Django 3.2.21 on 2024-09-02 19:48

import amelie.members.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0014_auto_20230918_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='suggested_picture',
            field=models.ImageField(blank=True, null=True, upload_to=amelie.members.models.person_picture_suggestion_upload_path, verbose_name='Suggested Photo'),
        ),
    ]
