# Generated by Django 4.2.21 on 2025-10-10 12:14

import amelie.members.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0015_alter_function_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='unverified_picture',
            field=models.ImageField(blank=True, null=True, upload_to=amelie.members.models.person_picture_upload_path, verbose_name='Unverified photo'),
        ),
    ]
