# Generated by Django 4.2.21 on 2025-09-01 18:49

from django.db import migrations
import logging

def get_console_logger():
    logger = logging.getLogger(__name__)
    handler = logging.StreamHandler()
    logger.addHandler(handler)
    logger.setLevel(logging.INFO)

    logger.info("starting logger")
    return logger

def flip_birthday_preference(apps, schema_editor):

    preference = apps.get_model('members', 'Preference')
    pref = preference.objects.filter(name='birthday_show_frontpage').first()

    assert pref is not None

    # Changes preference to inverted version
    pref.preference_nl = 'Ik wil dat mijn verjaardag zichtbaar is op de voorpagina.'
    pref.preference_en = 'I want my birthday to be publicly visible on the front page.'
    pref.save()

    person = apps.get_model('members', "Person")

    get_console_logger().info(f"person: {len(person.objects.all())}")

    # current state, this is all good
    persons_no_frontpage = person.objects.filter(preferences__name='birthday_show_frontpage')
    get_console_logger().info(f"no front (checked): {len(persons_no_frontpage)}")

    persons_frontpage = person.objects.exclude(preferences__name='birthday_show_frontpage')
    get_console_logger().info(f"front (unchecked): {len(persons_frontpage)}")


    # Set all people that do not want their birthday on the frontpage -> from check to uncheck
    for p in persons_no_frontpage:
        if p.id == 0:
            continue
        p.preferences.remove(pref) # This does not do its job
        p.save()

    # Set all people that do want their birthday on the frontpage -> from uncheck to check
    for p in persons_frontpage:
        if p.id == 0: # this is a thing?!?!
            continue
        p.preferences.add(pref) # went kaboom here because of id 0

class Migration(migrations.Migration):

    dependencies = [
        ('members', '0015_alter_function_options'),
    ]

    operations = [
        migrations.RunPython(flip_birthday_preference),
    ]
