# Generated by Django 4.2.21 on 2025-10-10 12:14

import amelie.members.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0016_person_is_portrait_picture_verified_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='is_portrait_picture_verified',
        ),
        migrations.RemoveField(
            model_name='person',
            name='portrait_picture',
        ),
        migrations.AddField(
            model_name='person',
            name='unverified_picture',
            field=models.ImageField(blank=True, null=True, upload_to=amelie.members.models.person_unverified_picture_upload_path, verbose_name='Unverified photo'),
        ),
    ]
