# Generated by Django 4.2.21 on 2025-09-01 18:49

from django.db import migrations
import logging

logger = logging.getLogger(__name__)
handler = logging.StreamHandler()
logger.addHandler(handler)
logger.setLevel(logging.INFO)

def flip_birthday_preference(apps, schema_editor):
    logger.info("starting birthday preference migration")

    preference = apps.get_model('members', 'Preference')
    pref = preference.objects.filter(name='birthday_show_frontpage').first()

    # If the preference does not exist, don't do anything, in case someone runs this on a blank (dev) DB
    if pref is None:
        return

    # Changes preference to the inverted version
    pref.preference_nl = 'Ik wil dat mijn verjaardag zichtbaar is op de voorpagina.'
    pref.preference_en = 'I want my birthday to be publicly visible on the front page.'
    pref.save()

    person = apps.get_model('members', "Person")

    logger.info(f"All persons: {len(person.objects.all())}")

    # current state, this is all good
    logger.info(f"Pre-migration old state:")
    persons_no_frontpage = person.objects.filter(preferences__name='birthday_show_frontpage')
    logger.info(f"- Not showing on frontpage (checked): {len(persons_no_frontpage)}")
    persons_frontpage = person.objects.exclude(preferences__name='birthday_show_frontpage')
    logger.info(f"- Showing on frontpage (unchecked): {len(persons_frontpage)}")


    # Set all people that do not want their birthday on the frontpage -> from check to uncheck
    for p in persons_no_frontpage:
        if p.id == 0:
            continue
        p.preferences.remove(pref) # This does not do its job
        p.save()

    # Set all people that do want their birthday on the frontpage -> from uncheck to check
    for p in persons_frontpage:
        if p.id == 0: # this is a thing?!?!
            continue
        p.preferences.add(pref) # went kaboom here because of id 0

    # new state, this should be inverted now
    logger.info(f"Post-migration new state (should match above):")
    persons_no_frontpage = person.objects.exclude(preferences__name='birthday_show_frontpage')
    logger.info(f"- Not showing on frontpage (unchecked): {len(persons_no_frontpage)}")
    persons_frontpage = person.objects.filter(preferences__name='birthday_show_frontpage')
    logger.info(f"- Showing on frontpage (checked): {len(persons_frontpage)}")

    logger.info("birthday preference migration completed.")


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0016_person_unverified_picture'),
    ]

    operations = [
        migrations.RunPython(flip_birthday_preference),
    ]
