# Generated by Django 4.2.26 on 2025-12-23 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0016_person_unverified_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='sudo_reset_code',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True, unique=True, verbose_name='Sudo password reset code'),
        ),
        migrations.AddField(
            model_name='person',
            name='sudo_reset_expiry',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Sudo password reset code expiry'),
        ),
    ]
