# Generated by Django 4.2.25 on 2025-10-28 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0016_person_unverified_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='cookie_corner_budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='cookie_corner_budget_action',
            field=models.CharField(choices=[('warning', 'Warning'), ('block', 'Block')], default='warning', max_length=8, verbose_name='Cookie corner over budget action'),
        ),
    ]
