# Generated by Django 5.2.9 on 2026-02-23 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0018_person_sudo_reset_code_person_sudo_reset_expiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='committee',
            name='matrix',
            field=models.BooleanField(default=False, help_text='Members of this committee get a private Matrix space', verbose_name='Create Matrix space'),
        ),
    ]
