# Generated by Django 5.2.14 on 2026-05-09 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0020_add_public_enrollment_preference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='webmaster',
        ),
    ]
