# Generated by Django 5.2.12 on 2026-06-25 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0020_add_public_enrollment_preference'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttype',
            name='visible',
            field=models.BooleanField(default=True, verbose_name='Visible'),
        ),
    ]
