# Generated by Django 5.2.12 on 2026-06-25 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0021_paymenttype_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='minecraft_username',
            field=models.CharField(blank=True, default='', max_length=16, verbose_name='Minecraft username'),
        ),
        migrations.AddField(
            model_name='person',
            name='minecraft_uuid',
            field=models.UUIDField(blank=True, null=True, verbose_name='Minecraft UUID'),
        ),
    ]
