# Generated by Django 5.2.12 on 2026-07-10 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0022_person_minecraft_username_person_minecraft_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='documenso_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Documenso ID'),
        ),
        migrations.AddField(
            model_name='membership',
            name='signed_document',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Signed document'),
        ),
        migrations.AddField(
            model_name='unverifiedenrollment',
            name='documenso_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Documenso ID'),
        ),
    ]
