# Generated by Django 5.2.12 on 2026-07-11 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0023_membership_documenso_id_membership_signed_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='unverifiedenrollment',
            name='documenso_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Documenso ID'),
        ),
    ]
