# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-25 22:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataExportInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('export_type', models.CharField(help_text='The type of export that was made.', max_length=100, verbose_name='Export type')),
                ('details', models.CharField(help_text='Details about the export, like applied filters, the object that was exported, etc. Empty often means that no filters have been applied.', max_length=512, verbose_name='Export details')),
                ('reason', models.CharField(help_text='The reason that the user gave for the export.', max_length=512, verbose_name='Reason for export')),
                ('exporter_text', models.CharField(help_text='String version of the exporter, for when their Person object is removed.', max_length=255, verbose_name='Name of exporter')),
                ('date', models.DateTimeField(auto_now_add=True, help_text='The date and time of the export.', verbose_name='Timestamp')),
                ('exporter', models.ForeignKey(help_text='The person that executed the export', null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.Person', verbose_name='Exporter')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile',
                'ordering': ['user'],
                'verbose_name_plural': 'Profiles',
            },
        ),
    ]
