# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-04-08 20:28
from __future__ import unicode_literals

from django.db import migrations, models
from django.conf import settings
from django.utils import timezone
from datetime import timezone as tz


def fill_old_rfid_created_used_dates(apps, schema_editor):
    RFIDCard = apps.get_model('personal_tab', 'RFIDCard')

    default_datetime = timezone.datetime(settings.DATE_OLD_RFID_CARDS.year, settings.DATE_OLD_RFID_CARDS.month,
                                         settings.DATE_OLD_RFID_CARDS.day, 0, 0, 0, 0, tz.utc)
    default_datetime = default_datetime - timezone.timedelta(days=1)

    for card in RFIDCard.objects.all():
        card.created = default_datetime
        card.last_used = default_datetime
        card.save()

class Migration(migrations.Migration):

    dependencies = [
        ('personal_tab', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfidcard',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creation date'),
        ),
        migrations.AddField(
            model_name='rfidcard',
            name='last_used',
            field=models.DateTimeField(auto_now_add=True, null=True,verbose_name='Date last used'),
        ),
        migrations.RunPython(fill_old_rfid_created_used_dates)
    ]
