# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-10-14 18:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personal_tab', '0002_auto_20190408_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledgeraccount',
            name='default_statistics',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='article',
            name='ledger_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='personal_tab.LedgerAccount', verbose_name='General ledger account'),
        ),
    ]
