# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-10-11 11:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('personal_tab', '0003_auto_20191014_2012'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingPosToken',
            fields=[
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('login', 'Login token'), ('registration', 'Registration token')], max_length=20)),
                ('created_at', models.DateTimeField(editable=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pending_pos_login_tokens', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='show_calculator_in_pos',
            field=models.BooleanField(default=False, help_text='The first active article in the category will be used for calculations.', verbose_name='Show the calculator in the Point of Sale instead of the products'),
        ),
    ]
