# Generated by Django 2.2.17 on 2020-11-03 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personal_tab', '0005_auto_20200921_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='personal_tab.Category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='authorization',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='members.Person', verbose_name='person'),
        ),
        migrations.AlterField(
            model_name='discountcredit',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='members.Person', verbose_name='added by'),
        ),
        migrations.AlterField(
            model_name='discountcredit',
            name='discount',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='personal_tab.Discount', verbose_name='discount'),
        ),
        migrations.AlterField(
            model_name='discountcredit',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='members.Person', verbose_name='person'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='members.Person', verbose_name='Added by'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='discount',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='personal_tab.Discount', verbose_name='discount'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='members.Person', verbose_name='Person'),
        ),
    ]
