# Generated by Django 2.2.20 on 2021-04-28 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal_tab', '0005_emandates'),
        ('personal_tab', '0006_auto_20201103_2220'),
    ]

    operations = [
    ]
