# Generated by Django 2.2.23 on 2021-06-14 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_tab', '0006_auto_20201103_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(max_length=255, upload_to='cookie_corner', verbose_name='Image'),
        ),
    ]
