# Generated by Django 2.2.24 on 2021-08-07 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal_tab', '0007_auto_20210614_2058'),
        ('personal_tab', '0007_merge_20210428_1903'),
    ]

    operations = [
    ]
