# Generated by Django 4.2.21 on 2025-10-17 15:42

import amelie.personal_tab.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0016_person_unverified_picture'),
        ('personal_tab', '0008_alter_article_ledger_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintLogEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('source_ip', models.CharField(blank=True, max_length=255, null=True)),
                ('source_useragent', models.CharField(blank=True, max_length=255, null=True)),
                ('document_name', models.CharField(max_length=255, verbose_name='Document name')),
                ('page_count', models.IntegerField(verbose_name='Page count')),
                ('actor', models.ForeignKey(on_delete=models.SET(amelie.personal_tab.models.get_sentinel_person), related_name='print_log', to='members.person', verbose_name='Actor')),
                ('committee', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='print_log', to='members.committee')),
                ('transaction', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='print_log', to='personal_tab.cookiecornertransaction')),
            ],
            options={'ordering': ['timestamp'], 'verbose_name': 'print log entry', 'verbose_name_plural': 'print log entries'},
        ),
    ]
