# Generated by Django 5.2.14 on 2026-06-02 08:58

import amelie.tools.fields
import uuid
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal_tab', '0009_printlogentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingpostoken',
            name='token',
            field=amelie.tools.fields.Char32UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
