# Generated by Django 5.2.12 on 2026-06-23 15:30

import django.db.models.deletion
import localflavor.generic.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0020_add_public_enrollment_preference'),
        ('personal_tab', '0009_printlogentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Declaration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.TextField(choices=[('BANK', 'Personal Bank'), ('CASHBOX', 'Inter-Actief Cashbox'), ('CARD', 'Inter-Actief Card')])),
                ('iban', localflavor.generic.models.IBANField(blank=True, include_countries=None, max_length=34, use_nordea_extensions=False, verbose_name='IBAN')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('document_names', models.TextField(blank=True, default=list)),
                ('submission_date', models.DateField(auto_now_add=True)),
                ('committee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.committee', verbose_name='committee')),
                ('person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.person', verbose_name='person')),
            ],
        ),
    ]
