# Generated by Django 5.2.12 on 2026-07-11 00:21

import localflavor.generic.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_tab', '0010_alter_pendingpostoken_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='BadBIC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bic', localflavor.generic.models.BICField(max_length=11, unique=True, verbose_name='BIC')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date added')),
            ],
            options={
                'verbose_name': 'known bad BIC',
                'verbose_name_plural': 'known bad BICs',
                'ordering': ['bic'],
            },
        ),
    ]
