# Generated by Django 5.2.12 on 2026-06-25 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_tab', '0010_alter_pendingpostoken_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountcredit',
            name='discount',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='personal_tab.discount', verbose_name='discount'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='discount',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='personal_tab.discount', verbose_name='discount'),
        ),
    ]
