# Generated by Django 5.2.12 on 2026-07-01 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_tab', '0010_declaration_squashed_0012_alter_declaration_committee_alter_declaration_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='declaration',
            name='document_names',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
