# Generated by Django 5.2.12 on 2026-07-10 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_tab', '0012_declaration'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorization',
            name='documenso_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Documenso ID'),
        ),
        migrations.AddField(
            model_name='authorization',
            name='signed_document',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Signed document'),
        ),
    ]
