# Generated by Django 5.2.12 on 2026-07-01 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_tab', '0013_alter_declaration_document_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='declaration',
            name='submission_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
