# Generated by Django 5.2.12 on 2026-07-23 14:13

import amelie.tools.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_tab', '0013_authorization_documenso_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingRegisterToken',
            fields=[
                ('token', amelie.tools.fields.Char32UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(editable=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pending_register_login_tokens', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
