# Generated by Django 5.2.12 on 2026-07-15 11:26

import django.db.models.deletion
import localflavor.generic.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_tab', '0013_authorization_documenso_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BadBIC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bic', localflavor.generic.models.BICField(max_length=11, unique=True, verbose_name='BIC')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Date added')),
                ('first_reversal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='personal_tab.reversal', verbose_name='First reversal')),
                ('last_reversal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='personal_tab.reversal', verbose_name='Last reversal')),
            ],
            options={
                'verbose_name': 'known bad BIC',
                'verbose_name_plural': 'known bad BICs',
                'ordering': ['bic'],
            },
        ),
    ]
