# Generated by Django 5.2.12 on 2026-07-16 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0023_documenso_id_signed_document'),
        ('personal_tab', '0013_authorization_documenso_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='declaration',
            name='bookkeeping',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='members.committee', verbose_name='bookkeeping'),
        ),
    ]
