# Generated by Django 5.2.12 on 2026-07-22 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_tab', '0013_authorization_documenso_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reversal',
            name='reason',
            field=models.CharField(choices=[('AC01', 'AC01 - IncorrectAccountNumber'), ('AC04', 'AC04 - ClosedAccountNumber'), ('AC06', 'AC06 - BlockedAccount'), ('AC13', 'AC13 - InvalidDebtorAccountType'), ('AG01', 'AG01 - TransactionForbidden'), ('AG02', 'AG02 - InvalidBankOperationCode'), ('AGNT', 'AGNT - IncorrectAgent'), ('AM04', 'AM04 - InsufficientFunds'), ('AM05', 'AM05 - Duplication'), ('BE05', 'BE05 - UnrecognisedInitiatingParty'), ('CURR', 'CURR - IncorrectCurrency'), ('CUST', 'CUST - RequestedByCustomer'), ('DNOR', 'DNOR - Debtor Bank is not registered under this BIC in the CSM'), ('DUPL', 'DUPL - DuplicatePayment'), ('FF01', 'FF01 - InvalidFileFormat'), ('FF05', 'FF05 - InvalidLocalInstrumentCode'), ('MD01', 'MD01 - NoMandate'), ('MD02', 'MD02 - MissingMandatoryInformationInMandate'), ('MD06', 'MD06 - RefundRequestByEndCustomer'), ('MD07', 'MD07 - EndCustomerDeceased'), ('MS02', 'MS02 - NotSpecifiedReasonCustomerGenerated'), ('MS03', 'MS03 - NotSpecifiedReasonAgentGenerated'), ('RC01', 'RC01 - BankIdentifierIncorrect'), ('RR01', 'RR01 - Missing Debtor Account or Identification'), ('RR02', 'RR02 - Missing Debtor Name or Address'), ('RR03', 'RR03 - Missing Creditor Name or Address'), ('RR04', 'RR04 - Regulatory Reason'), ('SL01', 'SL01 - Specific Service offered by Debtor Agent'), ('XXXX', 'XXXX - Debt collection cancelled by Inter-Actief')], max_length=4, verbose_name='reason'),
        ),
    ]
