# Generated by Django 2.2.17 on 2020-11-03 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='education.Course', verbose_name='Course'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='reporter',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='members.Person', verbose_name='Reporter'),
        ),
        migrations.AlterField(
            model_name='complaintcomment',
            name='person',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='members.Person', verbose_name='Person'),
        ),
        migrations.AlterField(
            model_name='page',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='education.Category'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='person',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='members.Person'),
        ),
    ]
