# Generated by Django 2.2.24 on 2021-11-15 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_auto_20201103_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaintcomment',
            name='official',
            field=models.BooleanField(default=False, verbose_name='Comment by Education(al) Affairs/Committee'),
        ),
    ]
