# Generated by Django 2.2.24 on 2021-11-15 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0003_complaintcomment_official'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaintcomment',
            name='official',
            field=models.BooleanField(default=False, editable=False, verbose_name='Comment by Education(al) Affairs/Committee'),
        ),
    ]
