# Generated by Django 3.2.16 on 2022-10-28 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0003_complaintcomment_official_squashed_0006_auto_20211211_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name_en',
            field=models.SlugField(blank=True, max_length=100, verbose_name='Name (en)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_nl',
            field=models.SlugField(max_length=100, verbose_name='Name'),
        ),
    ]
