# Generated by Django 3.2.16 on 2022-11-14 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0004_auto_20220530_2026'),
        ('education', '0004_auto_20221028_1502'),
    ]

    operations = [
    ]
