# Generated by Django 2.2.24 on 2021-11-15 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0004_auto_20211115_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaintcomment',
            name='official',
            field=models.BooleanField(default=False, editable=False, null=True, verbose_name='Comment by Education(al) Affairs/Committee'),
        ),
    ]
