# Generated by Django 3.2.16 on 2022-11-25 14:23
# Edited by Maarten

from django.db import migrations

def create_default_education_label(apps, schema_editor):
    ActivityLabel = apps.get_model('activities', 'ActivityLabel')

    # this part is just because we need this label in the database, in case it does not exist
    # if it already exists, this will do nothing
    obj, created = ActivityLabel.objects.get_or_create(
        name_en="Education",
        name_nl="Onderwijs",
        color="DC332E",
        icon="book_open",
        explanation_en="Educational",
        explanation_nl="Onderwijs-gerelateerd"
    )

class Migration(migrations.Migration):

    dependencies = [
        ('education', '0005_auto_20221028_1502'),
    ]

    operations = [
        migrations.RunPython(create_default_education_label),
    ]
