# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-25 22:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('calendar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='banners/')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(editable=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_nl', models.CharField(max_length=100, verbose_name='name')),
                ('name_en', models.CharField(blank=True, max_length=100, verbose_name='name (en)')),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('url', models.URLField()),
                ('logo', models.ImageField(blank=True, height_field='logo_height', null=True, upload_to='companies/logos/', width_field='logo_width')),
                ('logo_width', models.PositiveIntegerField(null=True)),
                ('logo_height', models.PositiveIntegerField(null=True)),
                ('profile_nl', models.TextField(verbose_name='profile')),
                ('profile_en', models.TextField(blank=True, verbose_name='profile (en)')),
                ('start_date', models.DateField(verbose_name='from')),
                ('end_date', models.DateField(verbose_name='until')),
                ('show_in_app', models.BooleanField(default=False, verbose_name='show in app')),
                ('app_logo', models.ImageField(blank=True, height_field='app_logo_height', null=True, upload_to='companies/app_logos/', width_field='app_logo_width')),
                ('app_logo_height', models.PositiveIntegerField(null=True)),
                ('app_logo_width', models.PositiveIntegerField(null=True)),
            ],
            options={
                'verbose_name': 'Company',
                'ordering': ['name_nl'],
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='CompanyEvent',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='calendar.Event')),
                ('company_text', models.CharField(blank=True, max_length=100)),
                ('company_url', models.URLField(blank=True)),
                ('visible_from', models.DateTimeField()),
                ('visible_till', models.DateTimeField()),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.Company')),
            ],
            bases=('calendar.event',),
        ),
        migrations.CreateModel(
            name='TelevisionBanner',
            fields=[
                ('basebanner_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='companies.BaseBanner')),
            ],
            options={
                'verbose_name': 'Television banner',
                'ordering': ['-end_date'],
                'verbose_name_plural': 'Television banners',
            },
            bases=('companies.basebanner',),
        ),
        migrations.CreateModel(
            name='WebsiteBanner',
            fields=[
                ('basebanner_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='companies.BaseBanner')),
                ('url', models.URLField()),
                ('views', models.PositiveIntegerField(default=0, editable=False)),
            ],
            options={
                'verbose_name': 'Website banner',
                'ordering': ['-end_date'],
                'verbose_name_plural': 'Website banners',
            },
            bases=('companies.basebanner',),
        ),
    ]
