# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-25 20:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_auto_20201103_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='short_description_en',
            field=models.CharField(max_length=120, blank=True, verbose_name='short description (en)'),
        ),
        migrations.AddField(
            model_name='company',
            name='short_description_nl',
            field=models.CharField(max_length=120, blank=True, verbose_name='short description'),
        ),
    ]
