# Generated by Django 3.2.16 on 2022-10-28 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_short_descriptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basebanner',
            name='slug',
            field=models.SlugField(editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='company',
            name='slug',
            field=models.SlugField(editable=False, max_length=100, unique=True),
        ),
    ]
