# Generated by Django 3.2.16 on 2023-02-06 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_televisionvideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='televisionvideo',
            name='video_type',
            field=models.CharField(choices=[('youtube', 'YouTube'), ('streamingia', 'StreamingIA')], default='streamingia', max_length=11),
        ),
    ]
