# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-11 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('narrowcasting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpotifyAssociation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=191, unique=True)),
                ('access_token', models.CharField(blank=True, max_length=191)),
                ('scopes', models.CharField(blank=True, max_length=191)),
                ('refresh_token', models.CharField(blank=True, max_length=191)),
            ],
        ),
    ]
