# Generated by Django 2.2.17 on 2020-11-03 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('narrowcasting', '0002_spotifyassociation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='televisionpromotion',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='activities.Activity'),
        ),
    ]
