# Generated by Django 3.2.25 on 2024-07-24 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('narrowcasting', '0003_auto_20201103_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotifyassociation',
            name='access_token',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='spotifyassociation',
            name='refresh_token',
            field=models.TextField(blank=True),
        ),
    ]
