# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-25 22:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='TwitterAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screenname', models.CharField(max_length=100, unique=True)),
                ('oauth_token', models.CharField(blank=True, max_length=100)),
                ('oauth_token_secret', models.CharField(blank=True, max_length=100)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_readonly', models.BooleanField(default=False)),
                ('last_tweet', models.CharField(blank=True, max_length=25)),
                ('last_update', models.DateTimeField(auto_now_add=True)),
                ('show_in_app', models.BooleanField(default=True)),
                ('image_url', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ['screenname', 'date_added'],
            },
        ),
        migrations.AddField(
            model_name='tweet',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='twitter.TwitterAccount'),
        ),
    ]
