# Generated by Django 2.2.17 on 2020-11-03 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='twitter.TwitterAccount'),
        ),
    ]
