# Generated by Django 4.2.16 on 2025-02-03 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0002_auto_20201103_2220'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tweet',
        ),
        migrations.DeleteModel(
            name='TwitterAccount',
        ),
    ]
