# Generated by Django 3.2.17 on 2023-09-22 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weekmail', '0002_auto_20201103_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weekmail',
            name='mailtype',
            field=models.CharField(choices=[('W', 'Weekly mail'), ('M', 'Mastermail'), ('E', 'Educational mail')], default='W', max_length=1, verbose_name='Type of mailing'),
        ),
    ]
