# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-25 22:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField(verbose_name='Starts on')),
                ('date_end', models.DateField(verbose_name='Ends on')),
                ('page', models.CharField(max_length=255, verbose_name='Page')),
                ('user_agent', models.CharField(blank=True, max_length=255, verbose_name='User-Agent')),
                ('hit_count', models.PositiveIntegerField(default=0, verbose_name='Hits')),
            ],
            options={
                'verbose_name': 'Hits',
                'verbose_name_plural': 'Hits',
            },
        ),
        migrations.AlterUniqueTogether(
            name='hits',
            unique_together=set([('date_start', 'page', 'user_agent')]),
        ),
    ]
