# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-25 22:00
from __future__ import unicode_literals

import amelie.calendar.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('files', '0001_initial'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin', models.DateTimeField(verbose_name='Starts')),
                ('end', models.DateTimeField(verbose_name='Ends')),
                ('entire_day', models.BooleanField(default=False, verbose_name='All dag')),
                ('summary_nl', models.CharField(max_length=250, verbose_name='Summary')),
                ('summary_en', models.CharField(blank=True, max_length=250, null=True, verbose_name='Summary (en)')),
                ('description_nl', models.TextField(blank=True, verbose_name='Description')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Description (en)')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Location')),
                ('public', models.BooleanField(default=True, verbose_name='Public')),
                ('dutch_activity', models.BooleanField(default=False, verbose_name='Dutch-only')),
                ('callback_url', models.CharField(blank=True, max_length=255, validators=[django.core.validators.RegexValidator(message='URL has to start with https://', regex='^https://.*'), django.core.validators.URLValidator()], verbose_name='Callback URL')),
                ('callback_secret_key', models.CharField(blank=True, default=amelie.calendar.models._generate_callback_secret_key, max_length=255)),
                ('update_count', models.PositiveIntegerField(default=0)),
                ('attachments', models.ManyToManyField(blank=True, to='files.Attachment', verbose_name='Attachments')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.Committee', verbose_name='Organizer')),
            ],
            options={
                'verbose_name': 'Activities',
                'ordering': ['begin'],
                'verbose_name_plural': 'Activities',
            },
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark', models.TextField(blank=True, verbose_name='Remarks')),
                ('payment_method', models.CharField(choices=[('-', 'No payment'), ('C', 'Cash at the board/committee'), ('M', 'Mandate')], max_length=1, verbose_name='Method of payment')),
                ('added_on', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Added on')),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='members.Person', verbose_name='Added by')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calendar.Event', verbose_name='Activities')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.Person', verbose_name='Person')),
            ],
            options={
                'verbose_name': 'Participation',
                'verbose_name_plural': 'Participations',
            },
        ),
        migrations.AddField(
            model_name='event',
            name='participants',
            field=models.ManyToManyField(blank=True, through='calendar.Participation', to='members.Person', verbose_name='Participants'),
        ),
        migrations.AlterUniqueTogether(
            name='participation',
            unique_together=set([('person', 'event')]),
        ),
    ]
