# Generated by Django 2.2.25 on 2022-02-07 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar', '0002_auto_20201103_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='promo_en',
            field=models.TextField(blank=True, help_text='This text can be used by the board for promotion, for example on our socials or in our weekmail. Let it be a teaser, so people would want to read your full activity description.', verbose_name='Short promotional message'),
        ),
        migrations.AddField(
            model_name='event',
            name='promo_nl',
            field=models.TextField(blank=True, help_text='This text can be used by the board for promotion, for example on our socials or in our weekmail. Let it be a teaser, so people would want to read your full activity description.', verbose_name='Short promotional message'),
        ),
    ]
