# Generated by Django 2.2.25 on 2022-06-03 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar', '0004_participation_waiting_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='participation',
            name='cash_payment_made',
            field=models.BooleanField(default=False, verbose_name='Cash payment made'),
        ),
    ]
