# Generated by Django 3.2.17 on 2023-09-18 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar', '0005_participation_cash_payment_made'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='cancelled',
            field=models.BooleanField(default=False, help_text='Whether this event is cancelled, only cancel when needed. Participants will receive an email notification!', verbose_name='Cancel event'),
        ),
    ]
