# Generated by Django 4.2.21 on 2025-10-15 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar', '0006_event_cancelled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='entire_day',
            field=models.BooleanField(default=False, verbose_name='All day'),
        ),
    ]
