# Generated by Django 5.2 on 2025-11-11 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar', '0007_alter_event_entire_day'),
        ('members', '0016_person_unverified_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='participants',
            field=models.ManyToManyField(blank=True, through='calendar.Participation', through_fields=('event', 'person'), to='members.person', verbose_name='Participants'),
        ),
    ]
