name: Retrieve CI job status from Inter-Actief GitLab
on:
  workflow_dispatch:
    inputs:
      result:
        description: 'Result of pipeline'
        required: true
        type: choice
        options:
        - success
        - failed
        - canceled
      details_url:
        description: 'URL to Job details on the IA GitLab'
        required: true
      job_id:
        description: 'The ID of the Job on the IA GitLab'
        required: true
jobs:
  test:
    name: Retrieve CI job status
    runs-on: ubuntu-latest
    steps:
    - name: Retrieve CI job status from Inter-Actief GitLab
      shell: bash
      run: |
        echo "Hello there." >> $GITHUB_STEP_SUMMARY
        echo "The result of job ${{ inputs.job_id }} was `${{ inputs.result }}`." >> $GITHUB_STEP_SUMMARY
        echo "See more info at [${{ inputs.details_url }}](${{ inputs.details_url }})." >> $GITHUB_STEP_SUMMARY
    - name: Fail if the result is failed
      if: ${{ inputs.result == 'failed' }}
      run: exit 1
