# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-25 22:00
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GMM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('agenda', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
            options={
                'verbose_name': 'GMM',
                'ordering': ['-date'],
                'verbose_name_plural': 'GMMs',
            },
        ),
    ]
