# Generated by Django 3.2.16 on 2022-11-23 11:27

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gmm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gmm',
            name='agenda',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
